name: lint_test_deploy
on: push
jobs:
  linting job:
    runs-on: ubuntu-latest
    steps:
      - name: Get the code from repo
        uses: actions/checkout@v3
      - name: Insall node
        uses: actions/setup-node@v3
      - name: Install the dependencies
        uses: npm ci
      - name: Run the linting script
        uses: 