name: lint_test_deploy
on: push
jobs:
  linting:
    runs-on: ubuntu-latest
    steps:
      - name: Get the code from repo
        uses: actions/checkout@v3
      # - name: Install node
      #   uses: actions/setup-node@v3
      - name: Install the dependencies
        uses: npm ci
      - name: Run the linting script
        uses: npm run lint
        run: echo 'Linting script successful!'
  
  testing:
    needs: linting
    runs-on: ubuntu-latest
    steps:
      - name: Get code from repo
        uses: actions/checkout@v3
      - name: Install the dependencies
        uses: npm ci
      - name: Run testing script
        use: npm run test
        run: echo 'Testing script successful!'
  
  deployment:
    needs: testing
    runs-on: ubuntu-latest
    steps:
      - name: Get code from repo
        uses: actions/checkout@v3
      - name: Install the dependencies
        uses: npm ci
      - name: Run the build script
        run: echo 'Deploying the code....'
